name: special_needs_app
description: تطبيق لذوي الاحتياجات الخاصة (إعاقة سمعية وبصرية)

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  shared_preferences: ^2.3.2
  file_picker: ^8.1.2
  flutter_launcher_icons: ^0.13.1
  device_info_plus: ^10.1.2  # ✅ للحصول على معلومات النظام

  vad: ^0.0.6    
  pdf: ^3.10.7
  printing: ^5.13.2
  google_fonts: ^6.2.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/fonts/

# 👇 قسم أيقونة التطبيق
flutter_launcher_icons:
  android: true
  image_path: "assets/images/logo.png"
  adaptive_icon_foreground: "assets/images/logo.png"
  #adaptive_icon_background: "#FFFFFF"
