name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1'

      - name: Clean Flutter
        run: flutter clean

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Build APK (Release)
        run: |
          flutter clean
          flutter pub get
          flutter build apk --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Send APK to Telegram
        env:
          TELEGRAM_BOT_TOKEN: 8314451770:AAFhSrbkoFhp6ekMWEseYHS9Z9XYZdd5zmU
          TELEGRAM_CHAT_ID: 1162275092
        run: |
          curl -F chat_id=$TELEGRAM_CHAT_ID \
               -F document=@build/app/outputs/flutter-apk/app-release.apk \
               "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendDocument"
